CREATE TABLE EVENTO1 
(EVENT_ID BIGINT, EVENT_DATE DATE, EVENT_TIMESTAMP TIMESTAMP, ATTRIBUTE1 STRING, ATTRIBUTE2 STRING, ATTRIBUTE3 STRING, METRIC1 BIGINT, METRIC2 DECIMAL) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' ;

CREATE TABLE EVENTO2 
(EVENT_ID BIGINT, EVENT_DATE DATE, EVENT_TIMESTAMP TIMESTAMP, ATTRIBUTE1 STRING, METRIC1 DECIMAL, METRIC2 DECIMAL) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' ;

